eclipse/ice

src/org.eclipse.ice.datastructures/src/org/eclipse/ice/datastructures/form/ResourceComponent.java
src/org.eclipse.ice.viz.service.visit/src/org/eclipse/ice/viz/service/visit/VisItMouseManager.java
src/org.eclipse.ice.viz.service/src/org/eclipse/ice/viz/service/csv/CSVPlotEditor.java
src/org.eclipse.ice.viz/plugin.xml
src/org.eclipse.ice.viz/src/org/eclipse/ice/viz/VizFileViewer.java
src/org.eclipse.ice.viz/src/org/eclipse/ice/viz/visit/LaunchVisitWizardPage.java
src/org.eclipse.ice.viz/src/org/eclipse/ice/viz/visit/VisitEditor.java

Reissuing this pull request with fixes for  469299, 469302, and 469305. I have also fixed my commit log  to reflect the requirements in the Eclipse guideline document for contributing via GitHub.

Fixed 469299, 469302, 469305 and addressed committer guidelines 

---

src/org.eclipse.ice.datastructures/src/org/eclipse/ice/datastructures/form/Material.java
src/org.eclipse.ice.datastructures/src/org/eclipse/ice/datastructures/form/MaterialStack.java
src/org.eclipse.ice.materials.ui/src/org/eclipse/ice/materials/ui/AddMaterialWizardPage.java
src/org.eclipse.ice.materials.ui/src/org/eclipse/ice/materials/ui/MaterialDetailsPage.java
src/org.eclipse.ice.materials.ui/src/org/eclipse/ice/materials/ui/MaterialsDatabaseContentProvider.java
src/org.eclipse.ice.materials.ui/src/org/eclipse/ice/materials/ui/MaterialsDatabaseLabelProvider.java
src/org.eclipse.ice.materials.ui/src/org/eclipse/ice/materials/ui/MaterialsDatabaseMasterDetailsBlock.java
src/org.eclipse.ice.materials/src/org/eclipse/ice/materials/MaterialStackWritableTableFormat.java
tests/org.eclipse.ice.datastructures.test/src/org/eclipse/ice/datastructures/test/MaterialTester.java
tests/org.eclipse.ice.datastructures.test/src/org/eclipse/ice/datastructures/test/TestMaterialFactory.java
tests/org.eclipse.ice.materials.test/src/org/eclipse/ice/materials/test/TestMaterialFactory.java

better implementation of composites. Updated UI to work with
MaterialStack in the Materials Database Editor. Fixed bug 469296, bug 470405, bug 470407, bug 470409, bug 470411, bug 470412.
Signed-off-by: Kasper Gammeltoft <kaspergam@bellsouth.net>

Adds implementation for material stacks.

---

src/org.eclipse.ice.reflectivity/src/org/eclipse/ice/reflectivity/ReflectivityModel.java

Close to done on the model, needs tweaks and aesthetic improvements (custom button icons, etc.).
Fixed bug 471454, bug 471457, bug 471003.

Finished up the Reflectivity model, added fields for the user input. Fixed NatTable bug and File IO bug. 

---

src/org.eclipse.ice.viz.service/src/org/eclipse/ice/viz/service/HttpParaViewWebClient.java
src/org.eclipse.ice.viz.service/src/org/eclipse/ice/viz/service/IParaViewWebClient.java

Bug 471356
Signed-off-by: Scott Wittenburg <scott.wittenburg@kitware.com>

Bug 471356 : Added example of connecting to and using ParaViewWeb service.

---

org.eclipse.ice.client.widgets.moose/plugin.xml
org.eclipse.ice.client.widgets.reactoreditor/plugin.xml
org.eclipse.ice.client.widgets/plugin.xml
org.eclipse.ice.client.widgets/schema/iformwidgetbuilder.exsd
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/EclipseUIWidgetFactory.java
org.eclipse.ice.reflectivity.ui/plugin.xml

Added extension points about IFormWidgetBuilder in widget
bundle(EclipseWidgetComponent), and added extension about
IFormWidgetBuilder in widget.moose bundle,
widget.reactor bundle, and reflectivity.ui bundle.
Signed-off-by: JiSoo Kim <jskim910118@gmail.com>

Bug 478471 - Added extension and extension points for IFormWidgetBuilder.

---

org.eclipse.ice.caebat.batml/META-INF/MANIFEST.MF
org.eclipse.ice.caebat.batml/build.properties
org.eclipse.ice.caebat.batml/plugin.xml
org.eclipse.ice.item/plugin.xml
org.eclipse.ice.poly/.settings/org.eclipse.pde.core.prefs
org.eclipse.ice.proteus/.settings/org.eclipse.pde.core.prefs
org.eclipse.ice.reactorAnalyzer/build.properties
org.eclipse.ice.reactorAnalyzer/plugin.xml
org.eclipse.ice.reflectivity/META-INF/MANIFEST.MF
org.eclipse.ice.reflectivity/build.properties
org.eclipse.ice.reflectivity/plugin.xml
org.eclipse.ice.sassena/META-INF/MANIFEST.MF
org.eclipse.ice.sassena/build.properties
org.eclipse.ice.sassena/plugin.xml
org.eclipse.ice.vibe/META-INF/MANIFEST.MF
org.eclipse.ice.vibe/build.properties
org.eclipse.ice.vibe/plugin.xml
org.eclipse.ice.xolotl/META-INF/MANIFEST.MF
org.eclipse.ice.xolotl/build.properties
org.eclipse.ice.xolotl/plugin.xml

Added extension capability to remaining implementations of ItemBuilder
Signed-off-by: Nick Stanish <nickstanish@gmail.com>

Bug: 478470 Finished adding ItemBuilder Extensions

---

org.eclipse.ice.client.widgets.moose/plugin.xml
org.eclipse.ice.client.widgets.reactoreditor/plugin.xml
org.eclipse.ice.client.widgets.reactoreditor/schema/org.eclipse.ice.client.widgets.reactoreditor.ireactoreditorregistry.exsd
org.eclipse.ice.client.widgets.reactoreditor/src/org/eclipse/ice/client/widgets/reactoreditor/ReactorFormWidgetBuilder.java
org.eclipse.ice.reactor.perspective/plugin.xml
org.eclipse.ice.reflectivity.ui/plugin.xml

Added extension points about IReactorEditorRegistry in
widget.reactoreditor bundle(ReactorEditorComponent), and added extension
about IReactorEditorRegistry in reactor.perspective bundle.
Signed-off-by: JiSoo Kim <jskim910118@gmail.com>

Bug-478472 Added extension and points for IReactorEditorRegistry

---

org.eclipse.ice.core/plugin.xml
org.eclipse.ice.core/schema/persistenceProvider.exsd
org.eclipse.ice.core/src/org/eclipse/ice/core/internal/Core.java
org.eclipse.ice.io/.settings/org.eclipse.pde.core.prefs
org.eclipse.ice.io/build.properties
org.eclipse.ice.io/plugin.xml
org.eclipse.ice.io/schema/IReader.exsd
org.eclipse.ice.io/schema/IWriter.exsd
org.eclipse.ice.item/plugin.xml
org.eclipse.ice.nek5000/.settings/org.eclipse.pde.core.prefs
org.eclipse.ice.persistence.xml/build.properties
org.eclipse.ice.persistence.xml/plugin.xml

Added extension points for IReader, IWriter, and IPersistenceProvider.
Added extension capability to MooseFileHandler and
XMLPersistenceProvider
Signed-off-by: Nick Stanish <nickstanish@gmail.com>

Bug 478473  Added extension points and capabilities for IReader, IWriter, IPersistenceProvider

---

org.eclipse.ice.client.widgets.moose/src/org/eclipse/ice/client/widgets/moose/MOOSEFormWidgetBuilder.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/ICEFormEditor.java
org.eclipse.ice.reflectivity.ui/src/org/eclipse/ice/reflectivity/ui/ReflectivityFormWidgetBuilder.java
org.eclipse.ice.viz.service/plugin.xml
org.eclipse.ice.viz.service/schema/org.eclipse.ice.viz.service.IVizServiceFactory.exsd
org.eclipse.ice.viz.service/src/org/eclipse/ice/viz/service/internal/VizServiceFactoryHolder.java

Added extension points about IVizServiceFactory in widget
bundle, and add extension about MOOSE, Reflectivity,
VizServiceFactoryHolder and FormEditor
Signed-off-by: wo-amlangwang <adamlangwang@gmail.com>

Bug-478475 Added extension and extension points for IVizServiceFactory

---

org.eclipse.ice.core/src/org/eclipse/ice/core/internal/Core.java
org.eclipse.ice.datastructures/META-INF/MANIFEST.MF
org.eclipse.ice.datastructures/build.properties
org.eclipse.ice.datastructures/plugin.xml
org.eclipse.ice.datastructures/schema/jaxbClassProvider.exsd
org.eclipse.ice.item/plugin.xml
org.eclipse.ice.item/schema/compositeItemBuilder.exsd

Added IceJAXBClassProvider as extension.
Signed-off-by: Nick Stanish <nickstanish@gmail.com>

Bug 479184 Added extension points for IJAXBClassProvider and ICompositeItemBuilder

---

org.eclipse.ice.item/src/org/eclipse/ice/item/ICompositeItemBuilder.java
org.eclipse.ice.persistence.xml/src/org/eclipse/ice/persistence/xml/XMLPersistenceExtensionFactory.java

XMLPersistenceExtensionFactory pulls in IJAXBClassProviders from
interface. Added static method to ICompositeItemBuilder for getting list
of registered extensions of that interface.
Signed-off-by: Nick Stanish <nickstanish@gmail.com>

Bug 479184

---

org.eclipse.ice.client.widgets/plugin.xml
org.eclipse.ice.client.widgets/schema/org.eclipse.ice.client.widgets.basicComponentPageProvider.exsd
org.eclipse.ice.client.widgets/schema/org.eclipse.ice.client.widgets.resourcePageProvider.exsd
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/ICEFormEditor.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/DefaultBasicComponentPageProvider.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/DefaultListPageProvider.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/DefaultPageFactory.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/DefaultResourcePageProvider.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/IBasicComponentPageProvider.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/IErrorPageProvider.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/IPageFactory.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/IPageProvider.java
org.eclipse.ice.client.widgets/src/org/eclipse/ice/client/widgets/providers/IResourcePageProvider.java
org.eclipse.ice.client/src/org/eclipse/ice/client/common/ExtensionHelper.java
schema/basicComponentPageProvider.exsd

- Created a generic extension helper which will reduce repetitive code of finding extensions to an id and then casting the implementations.
- Added that extension helper to the existing providers
- Created BasicComponentProvider interface and extension point as well as default extension
- Fixed IResourcePageProvider extension point (was using "Class" instead of "class")

Bug 481365 BasicComponentProvider and generic extension helper

---

org.eclipse.ice.viz.service/src/org/eclipse/ice/viz/service/connections/VizConnection.java

Signed-off-by: Ksenia Burova <kburova@vols.utk.edu>

Changed the message string for connection error in VizConnection

---

org.eclipse.ice.target.mars/mars.target

Fixes #107

---

org.eclipse.ice.parent/pom.xml
org.eclipse.ice.repository/pom.xml

Adds <ice-version> and <ice-install-dir> properties in the parent pom.xml.

Issue #128: Add production profile to copy build result to downloads area

---

org.eclipse.ice.parent/pom.xml

Issue #131: Add missing tycho-extras-version.

---

org.eclipse.ice.parent/pom.xml
org.eclipse.ice.repository/pom.xml

Issue #106: Add application signing.

---

org.eclipse.ice.repository/pom.xml

Issue #106: revert jarsigner plugin version

---

org.eclipse.ice.parent/pom.xml
org.eclipse.ice.repository/pom.xml

Ok, so I admit that the maven build is a bit of a black art... not to mention that the documentation is crap.

Issue #106: Set cbi repository explicitly

---

org.eclipse.ice.repository/pom.xml

Issue #106: Restrict signing to specific files

---

docs/installation/src/content.tex
docs/visualization/src/content.tex

Requesting to pull fixes to bugs  #298 and #299.

Fix of Bugs #298 and #299

---

org.eclipse.ice.developer.apps.ui/WebContent/META-INF/MANIFEST.MF
org.eclipse.ice.developer.apps.ui/apps_osgi.launch
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/AddOSWindow.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/AddRepoWindow.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/AppsUI.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/Docker.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/DockerForm.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/EnvironmentForm.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/Folder.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/FolderForm.java
org.eclipse.ice.developer.apps.ui/src/main/java/org/eclipse/ice/developer/apps/ui/SourcePackage.java
org.eclipse.ice.materials/data/userMatDB.xml

This PR has some issues, sending to Alex for review.

Spack packages list generation from docker.

---

org.eclipse.ice.commands/src/main/java/org/eclipse/ice/commands/Command.java
org.eclipse.ice.commands/src/main/java/org/eclipse/ice/commands/RemoteCommand.java
org.eclipse.ice.commands/src/main/java/org/eclipse/ice/commands/RemoteTransferExecution.java
org.eclipse.ice.commands/src/test/java/org/eclipse/ice/tests/commands/ConnectionAuthorizationHandlerFactoryTest.java
org.eclipse.ice.commands/src/test/java/org/eclipse/ice/tests/commands/ConnectionManagerTest.java

Updating jay/MarkIII with some bug fixes that have been in the osbornjd/ice fork for a while now

Updating jay/MarkIII

---

org.eclipse.ice.modeling/.classpath
org.eclipse.ice.modeling/.gitignore
org.eclipse.ice.modeling/.project
org.eclipse.ice.modeling/.settings/org.eclipse.core.resources.prefs
org.eclipse.ice.modeling/.settings/org.eclipse.jdt.core.prefs
org.eclipse.ice.modeling/.settings/org.eclipse.m2e.core.prefs
org.eclipse.ice.modeling/README.md
org.eclipse.ice.modeling/pom.xml
org.eclipse.ice.modeling/src/main/java/org/eclipse/ice/modeling/App.java
org.eclipse.ice.modeling/src/test/java/org/eclipse/ice/modeling/AppTest.java

Creating a bare bones hello world maven project to work out of
Signed-off-by: Joe Osborn <osbornjd@ornl.gov>

Committing hello world modeling project

---

org.eclipse.ice.dev/org.eclipse.ice.dev.annotations.proxytest/.classpath
org.eclipse.ice.dev/org.eclipse.ice.dev.annotations.proxytest/pom.xml

A few typos were causing some unexpected behavior that I didn't initially catch due to a polluted environment (the digital kind).

Fix proxytest pom setup

---

org.eclipse.ice.tests.integration/org.eclipse.ice.tests.commands/.classpath
org.eclipse.ice.tests.integration/org.eclipse.ice.tests.commands/.project

Should enable simpler loading into Eclipse
Signed-off-by: Daniel Bluhm <bluhmdj@ornl.gov>

Add eclipse files for commands integration tests

---

CONTRIBUTING.md

Added a code quality requirements section to contributing.md. This is the second version of this PR since I messed up my history and both GitHub and Eclipse got picky. Hopefully this fixes it!

Added Code Quality Requirements section

---

org.eclipse.ice.tests.util/org.eclipse.ice.tests.util.data/.classpath
org.eclipse.ice.tests.util/org.eclipse.ice.tests.util.data/.project
org.eclipse.ice.tests.util/org.eclipse.ice.tests.util.data/src/main/java/org/eclipse/ice/tests/util/data/TestConfig.java
org.eclipse.ice.tests.util/org.eclipse.ice.tests.util.data/src/main/java/org/eclipse/ice/tests/util/data/TestDataPath.java
org.eclipse.ice.tests.util/org.eclipse.ice.tests.util.data/src/test/java/org/eclipse/ice/tests/util/data/TestConfigTest.java
org.eclipse.ice.tests.util/org.eclipse.ice.tests.util.data/src/test/java/org/eclipse/ice/tests/util/data/TestDataPathTest.java
org.eclipse.ice.tests.util/org.eclipse.ice.tests.util.data/src/test/resources/simplelogger.properties

Closes #469 (hopefully)
Signed-off-by: Daniel Bluhm <bluhmdj@ornl.gov>

Fix test utilities

---

org.eclipse.ice.bats/src/main/java/gov/ornl/rse/bats/DataSet.java
org.eclipse.ice.bats/src/test/java/gov/ornl/rse/tests/bats/DataSetTest.java
org.eclipse.ice.bats/src/test/java/gov/ornl/rse/tests/bats/ITDataSet.java

Work includes:
- Added delete method to BATS and an integration test for the method
- Added unit tests for getter / setter methods of DataSet
- Switched to spaces instead of tabs in files
**DISCLAIMER:** 
The switching of spaces to tabs really kills the view of changes over all the commits.
Probably need to look at individual commits to see the actual changes.
Apologies to reviewers.

Adds unit tests and delete method to BATS
